# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('_description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('logo', models.ImageField(upload_to=b'sponsorzy/sponsor/logo', verbose_name='logo')),
                ('url', models.URLField(blank=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('sponsors', jsonfield.fields.JSONField(default={}, verbose_name='sponsors')),
                ('_html', models.TextField(blank=True, editable=False)),
                ('sprite', models.ImageField(blank=True, upload_to=b'sponsorzy/sprite')),
            ],
        ),
    ]
